In [47]:
import pandas as pd
from pandas import *
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sys
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import statsmodels.api as sm
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
%matplotlib inline
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
%config InlineBackend.figure_format='retina'
f = r'C:\Users\jflan\Downloads\Employment_Wages_in_Colorado.csv'

In [48]:
df= pandas.read_csv(f)
print(len(df))

83407

In [49]:
print(df.keys())
print(len(df.keys()))
df.drop(columns=['stateabbrv','statename','panelcode','period','indcode','response'])

Index(['stateabbrv', 'statename', 'stfips', 'areaname', 'areatype',
       'areatyname', 'area', 'periodyear', 'periodtype', 'pertypdesc',
       'period', 'indcodty', 'indcode', 'indcodetitle', 'occodetype',
       'occodetydesc', 'occcode', 'codetitle', 'wagesource', 'wagesrdesc',
       'ratetype', 'ratetydesc', 'empcount', 'response', 'mean', 'entrywg',
       'experience', 'pct10', 'pct25', 'median', 'pct75', 'pct90', 'udpct',
       'udpctwage', 'udrnglopct', 'udrnghipct', 'udrngmean', 'wpctrelerr',
       'epctrelerr', 'panelcode'],
      dtype='object')
40

,stfips,areaname,areatype,areatyname,area,periodyear,periodtype,pertypdesc,indcodty,indcodetitle,...,median,pct75,pct90,udpct,udpctwage,udrnglopct,udrnghipct,udrngmean,wpctrelerr,epctrelerr
0,8,Colorado,1,State,0,2010,1,Annual,10,Total All,...,17.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.40
1,8,Colorado,1,State,0,2010,1,Annual,10,Total All,...,36851.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.40
2,8,Colorado,1,State,0,2011,1,Annual,10,Total All,...,17.82,28.30,42.85,NaN,NaN,NaN,NaN,NaN,0.50,0.39
3,8,Colorado,1,State,0,2011,1,Annual,10,Total All,...,37068.00,58867.00,89135.00,NaN,NaN,NaN,NaN,NaN,0.50,0.39
4,8,Boulder-Longmont MSA,21,Metropolitan Statistical Area,14500,2010,1,Annual,10,Total All,...,19.51,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.42
5,8,Boulder-Longmont MSA,21,Metropolitan Statistical Area,14500,2010,1,Annual,10,Total All,...,40579.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.42
6,8,Boulder-Longmont MSA,21,Metropolitan Statistical Area,14500,2011,1,Annual,10,Total All,...,19.69,32.56,51.56,NaN,NaN,NaN,NaN,NaN,2.01,1.49
7,8,Boulder-Longmont MSA,21,Metropolitan Statistical Area,14500,2011,1,Annual,10,Total All,...,40951.00,67731.00,107237.00,NaN,NaN,NaN,NaN,NaN,2.01,1.49
8,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2011,1,Annual,10,Total All,...,16.88,27.42,41.63,NaN,NaN,NaN,NaN,NaN,2.03,1.09
9,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2011,1,Annual,10,Total All,...,35100.00,57044.00,86582.00,NaN,NaN,NaN,NaN,NaN,2.03,1.09
10,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2010,1,Annual,10,Total All,...,16.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.10
11,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2010,1,Annual,10,Total All,...,34779.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.10
12,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2010,1,Annual,10,Total All,...,18.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49
13,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2010,1,Annual,10,Total All,...,38894.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.49
14,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2011,1,Annual,10,Total All,...,18.86,30.20,45.07,NaN,NaN,NaN,NaN,NaN,1.02,0.48
15,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2011,1,Annual,10,Total All,...,39231.00,62808.00,93737.00,NaN,NaN,NaN,NaN,NaN,1.02,0.48
16,8,Fort Collins-Loveland MSA,21,Metropolitan Statistical Area,22660,2010,1,Annual,10,Total All,...,16.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.04
17,8,Fort Collins-Loveland MSA,21,Metropolitan Statistical Area,22660,2010,1,Annual,10,Total All,...,34654.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.04
18,8,Fort Collins-Loveland MSA,21,Metropolitan Statistical Area,22660,2011,1,Annual,10,Total All,...,16.77,26.40,39.76,NaN,NaN,NaN,NaN,NaN,2.23,1.27
19,8,Fort Collins-Loveland MSA,21,Metropolitan Statistical Area,22660,2011,1,Annual,10,Total All,...,34891.00,54906.00,82692.00,NaN,NaN,NaN,NaN,NaN,2.23,1.27
20,8,Grand Junction MSA,21,Metropolitan Statistical Area,24300,2011,1,Annual,10,Total All,...,15.63,23.51,33.85,NaN,NaN,NaN,NaN,NaN,1.99,1.36
21,8,Grand Junction MSA,21,Metropolitan Statistical Area,24300,2011,1,Annual,10,Total All,...,32513.00,48903.00,70403.00,NaN,NaN,NaN,NaN,NaN,1.99,1.36
22,8,Grand Junction MSA,21,Metropolitan Statistical Area,24300,2010,1,Annual,10,Total All,...,15.49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.66
23,8,Grand Junction MSA,21,Metropolitan Statistical Area,24300,2010,1,Annual,10,Total All,...,32217.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.66
24,8,Greeley MSA,21,Metropolitan Statistical Area,24540,2010,1,Annual,10,Total All,...,16.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.34
25,8,Greeley MSA,21,Metropolitan Statistical Area,24540,2010,1,Annual,10,Total All,...,33503.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.34
26,8,Greeley MSA,21,Metropolitan Statistical Area,24540,2011,1,Annual,10,Total All,...,16.19,24.30,35.57,NaN,NaN,NaN,NaN,NaN,1.87,4.54
27,8,Greeley MSA,21,Metropolitan Statistical Area,24540,2011,1,Annual,10,Total All,...,33671.00,50546.00,73982.00,NaN,NaN,NaN,NaN,NaN,1.87,4.54
28,8,Pueblo MSA,21,Metropolitan Statistical Area,39380,2011,1,Annual,10,Total All,...,14.95,22.55,33.10,NaN,NaN,NaN,NaN,NaN,2.51,2.30
29,8,Pueblo MSA,21,Metropolitan Statistical Area,39380,2011,1,Annual,10,Total All,...,31086.00,46912.00,68857.00,NaN,NaN,NaN,NaN,NaN,2.51,2.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83377,8,Colorado,1,State,0,2015,1,Annual,10,Total All,...,27.59,29.60,31.17,NaN,NaN,NaN,NaN,NaN,2.76,36.65
83378,8,Colorado,1,State,0,2015,1,Annual,10,Total All,...,57384.00,61574.00,64835.00,NaN,NaN,NaN,NaN,NaN,2.76,36.65
83379,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,29.54,31.58,35.58,0.0,NaN,0.0,0.0,NaN,2.91,40.17
83380,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,61434.00,65691.00,74007.00,0.0,NaN,0.0,0.0,NaN,2.91,40.17
83381,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,21.45,24.28,29.23,0.0,NaN,0.0,0.0,NaN,3.77,14.82
83382,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,44609.00,50505.00,60794.00,0.0,NaN,0.0,0.0,NaN,3.77,14.82
83383,8,Colorado,1,State,0,2016,1,Annual,10,Total All,...,21.47,25.77,30.27,0.0,NaN,0.0,0.0,NaN,4.34,23.30
83384,8,Colorado,1,State,0,2016,1,Annual,10,Total All,...,44649.00,53600.00,62968.00,0.0,NaN,0.0,0.0,NaN,4.34,23.30
83385,8,Colorado,1,State,0,2013,1,Annual,10,Total All,...,15.23,20.58,26.61,NaN,NaN,NaN,NaN,NaN,14.38,31.23
83386,8,Colorado,1,State,0,2013,1,Annual,10,Total All,...,31672.00,42805.00,55340.00,NaN,NaN,NaN,NaN,NaN,14.38,31.23
83387,8,Colorado,1,State,0,2012,1,Annual,10,Total All,...,13.41,16.67,18.83,NaN,NaN,NaN,NaN,NaN,9.88,38.25
83388,8,Colorado,1,State,0,2012,1,Annual,10,Total All,...,27883.00,34676.00,39166.00,NaN,NaN,NaN,NaN,NaN,9.88,38.25
83389,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2017,1,Annual,10,Total All,...,21.92,23.98,27.65,0.0,NaN,0.0,0.0,NaN,3.89,33.00
83390,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2017,1,Annual,10,Total All,...,45595.00,49869.00,57506.00,0.0,NaN,0.0,0.0,NaN,3.89,33.00
83391,8,Southwest Colorado,75,Balance of State,80002,2017,1,Annual,10,Total All,...,17.80,20.67,27.35,0.0,NaN,0.0,0.0,NaN,4.53,34.58
83392,8,Southwest Colorado,75,Balance of State,80002,2017,1,Annual,10,Total All,...,37023.00,42987.00,56898.00,0.0,NaN,0.0,0.0,NaN,4.53,34.58
83393,8,Pueblo MSA,21,Metropolitan Statistical Area,39380,2013,1,Annual,10,Total All,...,20.86,20.87,22.12,NaN,NaN,NaN,NaN,NaN,4.45,5.13
83394,8,Pueblo MSA,21,Metropolitan Statistical Area,39380,2013,1,Annual,10,Total All,...,43393.00,43406.00,46004.00,NaN,NaN,NaN,NaN,NaN,4.45,5.13
83395,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2016,1,Annual,10,Total All,...,17.44,19.14,23.23,0.0,NaN,0.0,0.0,NaN,7.32,36.16
83396,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2016,1,Annual,10,Total All,...,36277.00,39808.00,48313.00,0.0,NaN,0.0,0.0,NaN,7.32,36.16
83397,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2017,1,Annual,10,Total All,...,14.36,16.51,18.81,0.0,NaN,0.0,0.0,NaN,4.47,7.21
83398,8,Colorado Springs MSA,21,Metropolitan Statistical Area,17820,2017,1,Annual,10,Total All,...,29879.00,34339.00,39126.00,0.0,NaN,0.0,0.0,NaN,4.47,7.21
83399,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2013,1,Annual,10,Total All,...,12.07,16.31,24.73,NaN,NaN,NaN,NaN,NaN,6.12,9.27
83400,8,Denver - Aurora MSA,21,Metropolitan Statistical Area,19740,2013,1,Annual,10,Total All,...,25100.00,33935.00,51429.00,NaN,NaN,NaN,NaN,NaN,6.12,9.27
83401,8,Colorado,1,State,0,2013,1,Annual,10,Total All,...,12.55,18.07,24.33,NaN,NaN,NaN,NaN,NaN,6.39,8.44
83402,8,Colorado,1,State,0,2013,1,Annual,10,Total All,...,26104.00,37590.00,50602.00,NaN,NaN,NaN,NaN,NaN,6.39,8.44
83403,8,Colorado,1,State,0,2016,1,Annual,10,Total All,...,18.76,22.02,24.59,0.0,NaN,0.0,0.0,NaN,5.36,22.02
83404,8,Colorado,1,State,0,2016,1,Annual,10,Total All,...,39012.00,45810.00,51151.00,0.0,NaN,0.0,0.0,NaN,5.36,22.02
83405,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,18.35,20.92,23.87,0.0,NaN,0.0,0.0,NaN,4.44,33.92
83406,8,Colorado,1,State,0,2017,1,Annual,10,Total All,...,38169.00,43517.00,49657.00,0.0,NaN,0.0,0.0,NaN,4.44,33.92

In [50]:
first_value=df.head(1)
print(first_value.transpose())

                                                      0
stateabbrv                                           CO
statename                                      Colorado
stfips                                                8
areaname                                       Colorado
areatype                                              1
areatyname                                        State
area                                                  0
periodyear                                         2010
periodtype                                            1
pertypdesc                                       Annual
period                                                0
indcodty                                             10
indcode                                               0
indcodetitle                                  Total All
occodetype                                            8
occodetydesc                                   SOC 2000
occcode                                               0
codetitle                         Total All occupations
wagesource                                            3
wagesrdesc    Occupational Employment Statistics Survey
ratetype                                              1
ratetydesc                                  Hourly wage
empcount                                        2157690
response                                             78
mean                                              22.48
entrywg                                           10.05
experience                                         28.7
pct10                                              8.68
pct25                                             11.55
median                                            17.72
pct75                                               NaN
pct90                                               NaN
udpct                                               NaN
udpctwage                                           NaN
udrnglopct                                          NaN
udrnghipct                                          NaN
udrngmean                                           NaN
wpctrelerr                                          NaN
epctrelerr                                          0.4
panelcode                                           NaN

In [51]:
print(df['ratetype'].unique())
print(df['ratetype'])

[1 4]
0        1
1        4
2        1
3        4
4        1
        ..
83402    4
83403    1
83404    4
83405    1
83406    4
Name: ratetype, Length: 83407, dtype: int64

In [52]:
print(df['codetitle'])

0                     Total All occupations
1                     Total All occupations
2                     Total All occupations
3                     Total All occupations
4                     Total All occupations
                        ...
83402    Material Moving Workers, All Other
83403    Material Moving Workers, All Other
83404    Material Moving Workers, All Other
83405    Material Moving Workers, All Other
83406    Material Moving Workers, All Other
Name: codetitle, Length: 83407, dtype: object

In [53]:
#Data cleaning

#Let's see if we can find which columns contain blanks and which ones are filled out completely
df.isna().any()

stateabbrv      False
statename       False
stfips          False
areaname        False
areatype        False
areatyname      False
area            False
periodyear      False
periodtype      False
pertypdesc      False
period          False
indcodty        False
indcode         False
indcodetitle    False
occodetype      False
occodetydesc    False
occcode         False
codetitle       False
wagesource      False
wagesrdesc      False
ratetype        False
ratetydesc      False
empcount        False
response        False
mean             True
entrywg          True
experience       True
pct10            True
pct25            True
median           True
pct75            True
pct90            True
udpct            True
udpctwage        True
udrnglopct       True
udrnghipct       True
udrngmean        True
wpctrelerr       True
epctrelerr      False
panelcode        True
dtype: bool

In [54]:
#Of the columns that contain blanks what percentage of those columns are blank
for column in df:
        if df[column].isnull().any():
            print('{0} has {1} null values, {2} percent is missing.'.format(column, df[column].isnull().sum(), str(round(100*df[column].isnull().sum()/83408))))

mean has 1742 null values, 2.0 percent is missing.
entrywg has 1912 null values, 2.0 percent is missing.
experience has 1974 null values, 2.0 percent is missing.
pct10 has 1762 null values, 2.0 percent is missing.
pct25 has 1852 null values, 2.0 percent is missing.
median has 2083 null values, 2.0 percent is missing.
pct75 has 11082 null values, 13.0 percent is missing.
pct90 has 11958 null values, 14.0 percent is missing.
udpct has 56179 null values, 67.0 percent is missing.
udpctwage has 74887 null values, 90.0 percent is missing.
udrnglopct has 56179 null values, 67.0 percent is missing.
udrnghipct has 56179 null values, 67.0 percent is missing.
udrngmean has 74887 null values, 90.0 percent is missing.
wpctrelerr has 9091 null values, 11.0 percent is missing.
panelcode has 35651 null values, 43.0 percent is missing.

In [55]:
duplicates= df[df.duplicated()]
print(len(duplicates))
# no duplicate rows! However, we still have summary rows. Let's remove all rows that are of a summary and see if that removes some holes in the data
print(df['areatyname'].unique())

0
['State' 'Metropolitan Statistical Area' 'Balance of State (pre-2015)'
 'Balance of State']

In [56]:
#we want to remove anything that isn't a metropolitan statistical area
df= df.loc[df['areatyname']== 'Metropolitan Statistical Area']
print(len(df))
for column in df:
        if df[column].isnull().any():
            print('{0} has {1} null values, {2} percent is missing.'.format(column, df[column].isnull().sum(), str(round(100*df[column].isnull().sum()/83408))))

50612
mean has 1013 null values, 1.0 percent is missing.
entrywg has 1121 null values, 1.0 percent is missing.
experience has 1155 null values, 1.0 percent is missing.
pct10 has 1029 null values, 1.0 percent is missing.
pct25 has 1089 null values, 1.0 percent is missing.
median has 1220 null values, 1.0 percent is missing.
pct75 has 6522 null values, 8.0 percent is missing.
pct90 has 7121 null values, 9.0 percent is missing.
udpct has 33539 null values, 40.0 percent is missing.
udpctwage has 45191 null values, 54.0 percent is missing.
udrnglopct has 33539 null values, 40.0 percent is missing.
udrnghipct has 33539 null values, 40.0 percent is missing.
udrngmean has 45191 null values, 54.0 percent is missing.
wpctrelerr has 5453 null values, 7.0 percent is missing.
panelcode has 21720 null values, 26.0 percent is missing.

In [57]:
print(df['areaname'].unique())

['Boulder-Longmont MSA' 'Colorado Springs MSA' 'Denver - Aurora MSA'
 'Fort Collins-Loveland MSA' 'Grand Junction MSA' 'Greeley MSA'
 'Pueblo MSA']

In [58]:
#Add in population data
f1= r'C:\Users\jflan\Downloads\Population_Estimates_by_Year_for_Counties_in_Colorado_2015.csv'
pop_data= pandas.read_csv(f1)
print(len(pop_data))
print(pop_data.keys())

3082
Index(['stateabbrv', 'statename', 'stfips', 'areaname', 'areatype',
       'areatyname', 'area', 'periodyear', 'periodtype', 'pertypdesc',
       'period', 'popsource', 'popsrcdesc', 'population', 'releasedate'],
      dtype='object')

In [59]:
#Let's drop all data that isn't annual
df=df.loc[df['ratetydesc']=='Annual wage or salary']
#How has it changed null values
for column in df:
        if df[column].isnull().any():
            print('{0} has {1} null values, {2} percent is missing.'.format(column, df[column].isnull().sum(), str(round(100*df[column].isnull().sum()/83408))))

mean has 50 null values, 0.0 percent is missing.
entrywg has 104 null values, 0.0 percent is missing.
experience has 121 null values, 0.0 percent is missing.
pct10 has 58 null values, 0.0 percent is missing.
pct25 has 88 null values, 0.0 percent is missing.
median has 154 null values, 0.0 percent is missing.
pct75 has 2860 null values, 3.0 percent is missing.
pct90 has 3167 null values, 4.0 percent is missing.
udpct has 16883 null values, 20.0 percent is missing.
udpctwage has 22709 null values, 27.0 percent is missing.
udrnglopct has 16883 null values, 20.0 percent is missing.
udrnghipct has 16883 null values, 20.0 percent is missing.
udrngmean has 22709 null values, 27.0 percent is missing.
wpctrelerr has 2781 null values, 3.0 percent is missing.
panelcode has 11020 null values, 13.0 percent is missing.

In [60]:
df = df[df.codetitle != 'Total All occupations']
#let's also drop those columns above that we won't be using down the line 
df.drop(columns=['epctrelerr','periodtype','pertypdesc','period','areatype','stateabbrv', 'statename', 'stfips','panelcode','wpctrelerr','udrngmean','udrnghipct','udrnglopct','udpctwage','udpct'],inplace=True)
df.keys()
print(df.shape)

(25410, 25)

In [61]:
#Add in population data
f1= r'C:\Users\jflan\Downloads\Population_Estimates_by_Year_for_Counties_in_Colorado_2015.csv'
pop_data= pandas.read_csv(f1)
print(len(pop_data))
print(pop_data.keys())

3082
Index(['stateabbrv', 'statename', 'stfips', 'areaname', 'areatype',
       'areatyname', 'area', 'periodyear', 'periodtype', 'pertypdesc',
       'period', 'popsource', 'popsrcdesc', 'population', 'releasedate'],
      dtype='object')

In [62]:
pop_data=pop_data.loc[pop_data['areatyname']=='County']
print(len(pop_data))

2850

In [63]:
pop_data=pop_data[(pop_data.periodyear >= 2009)]
print(len(pop_data))

384

In [64]:
#Denver-Aurora MSA
pop_data['areaname']=pop_data['areaname'].replace("Denver County","Denver - Aurora MSA")
pop_data['areaname']=pop_data['areaname'].replace("Jefferson County","Denver - Aurora MSA")
pop_data['areaname']=pop_data['areaname'].replace("Arapahoe County","Denver - Aurora MSA")
pop_data['areaname']=pop_data['areaname'].replace("Adams County","Denver - Aurora MSA")
pop_data['areaname']=pop_data['areaname'].replace("Douglas County","Denver - Aurora MSA")
pop_data['areaname']=pop_data['areaname'].replace("Elbert County","Denver - Aurora MSA")

#Boulder-Longmont MSA
pop_data['areaname']=pop_data['areaname'].replace("Broomfield County","Boulder-Longmont MSA")
pop_data['areaname']=pop_data['areaname'].replace("Boulder County","Boulder-Longmont MSA")
pop_data['areaname']=pop_data['areaname'].replace("Gilpin County","Boulder-Longmont MSA")
#Pueblo MSA
pop_data['areaname']=pop_data['areaname'].replace("Pueblo County","Pueblo MSA")
#Grand Junction MSA
pop_data['areaname']=pop_data['areaname'].replace("Mesa County","Grand Junction MSA")
#Colorado Springs MSA
pop_data['areaname']=pop_data['areaname'].replace("El Paso County","Colorado Springs MSA")
pop_data['areaname']=pop_data['areaname'].replace("Teller County","Colorado Springs MSA")
#Fort Collins-Loveland MSA
pop_data['areaname']=pop_data['areaname'].replace("Larimer County","Fort Collins-Loveland MSA")
#Greely MSA
pop_data['areaname']=pop_data['areaname'].replace("Weld County","Greeley MSA")
print(sorted(pop_data['areaname'].unique()))

['Alamosa County', 'Archuleta County', 'Baca County', 'Bent County', 'Boulder-Longmont MSA', 'Chaffee County', 'Cheyenne County', 'Clear Creek County', 'Colorado Springs MSA', 'Conejos County', 'Costilla County', 'Crowley County', 'Custer County', 'Delta County', 'Denver - Aurora MSA', 'Dolores County', 'Eagle County', 'Fort Collins-Loveland MSA', 'Fremont County', 'Garfield County', 'Grand County', 'Grand Junction MSA', 'Greeley MSA', 'Gunnison County', 'Hinsdale County', 'Huerfano County', 'Jackson County', 'Kiowa County', 'Kit Carson County', 'La Plata County', 'Lake County', 'Las Animas County', 'Lincoln County', 'Logan County', 'Mineral County', 'Moffat County', 'Montezuma County', 'Montrose County', 'Morgan County', 'Otero County', 'Ouray County', 'Park County', 'Phillips County', 'Pitkin County', 'Prowers County', 'Pueblo MSA', 'Rio Blanco County', 'Rio Grande County', 'Routt County', 'Saguache County', 'San Juan County', 'San Miguel County', 'Sedgwick County', 'Summit County', 'Washington County', 'Yuma County']

In [65]:
pop_data.to_csv(r'C:\Users\jflan\Downloads\Counties_Employment_Wages_in_Colorado.csv')

In [66]:
pop_data=pop_data.drop(['stateabbrv', 'statename', 'stfips', 'areatype',
       'areatyname', 'area', 'periodtype', 'pertypdesc',
       'period', 'popsource', 'popsrcdesc', 'releasedate'],axis=1)

In [67]:
#MSA=['Pueblo MSA' 'Greeley MSA' 'Grand Junction MSA'
 #'Fort Collins-Loveland MSA' 'Denver - Aurora MSA' 'Colorado Springs MSA'
 #'Boulder-Longmont MSA']
pop_data=pop_data[~pop_data.areaname.str.contains("County")]

In [68]:
print(pop_data['areaname'].unique())
print(pop_data.shape)

['Denver - Aurora MSA' 'Colorado Springs MSA' 'Grand Junction MSA'
 'Fort Collins-Loveland MSA' 'Boulder-Longmont MSA' 'Greeley MSA'
 'Pueblo MSA']
(90, 3)

In [69]:
pop_data['population'] = pop_data['population'].str.replace(',', '')

In [70]:
pop_data['population']=pd.to_numeric(pop_data['population'])

In [71]:
#pop_data.groupby(['areaname','periodyear']).sum()
#print(pop_data)

In [72]:
#pop_data=pop_data.groupby(['areaname','periodyear'])['population'].agg('sum')
#print(pop_data)

In [73]:
pop_table=pandas.pivot_table(pop_data,values='population',columns='periodyear',index='areaname',aggfunc=np.sum)
pop_table
pop=[]

In [74]:
pop=pop_table
pop.keys()
pop['2015']= [386437,695204,2713881,331933,148813,284966,162431]
print(pop)

periodyear                    2009     2010     2011     2012     2013  \
areaname
Boulder-Longmont MSA        353331   355897   363530   369928   376274
Colorado Springs MSA        630998   645613   660278   669100   678711
Denver - Aurora MSA        2424184  2456858  2512795  2558201  2608634
Fort Collins-Loveland MSA   296696   299630   305241   310835   316494
Grand Junction MSA          147851   146723   147380   147724   147699
Greeley MSA                 248193   252825   258737   264189   270560
Pueblo MSA                  157846   159063   160213   160840   161320

periodyear                    2014     2015
areaname
Boulder-Longmont MSA        381322   386437
Colorado Springs MSA        686908   695204
Denver - Aurora MSA        2660737  2713881
Fort Collins-Loveland MSA   324122   331933
Grand Junction MSA          148255   148813
Greeley MSA                 277670   284966
Pueblo MSA                  161875   162431

In [75]:
pop=pop.stack(0).reset_index()
print(pop.keys())

Index(['areaname', 'periodyear', 0], dtype='object')

In [76]:
pop.rename(columns={0:'population'},inplace=True)
print(pop.keys())
print(pop)

Index(['areaname', 'periodyear', 'population'], dtype='object')
                     areaname periodyear  population
0        Boulder-Longmont MSA       2009      353331
1        Boulder-Longmont MSA       2010      355897
2        Boulder-Longmont MSA       2011      363530
3        Boulder-Longmont MSA       2012      369928
4        Boulder-Longmont MSA       2013      376274
5        Boulder-Longmont MSA       2014      381322
6        Boulder-Longmont MSA       2015      386437
7        Colorado Springs MSA       2009      630998
8        Colorado Springs MSA       2010      645613
9        Colorado Springs MSA       2011      660278
10       Colorado Springs MSA       2012      669100
11       Colorado Springs MSA       2013      678711
12       Colorado Springs MSA       2014      686908
13       Colorado Springs MSA       2015      695204
14        Denver - Aurora MSA       2009     2424184
15        Denver - Aurora MSA       2010     2456858
16        Denver - Aurora MSA       2011     2512795
17        Denver - Aurora MSA       2012     2558201
18        Denver - Aurora MSA       2013     2608634
19        Denver - Aurora MSA       2014     2660737
20        Denver - Aurora MSA       2015     2713881
21  Fort Collins-Loveland MSA       2009      296696
22  Fort Collins-Loveland MSA       2010      299630
23  Fort Collins-Loveland MSA       2011      305241
24  Fort Collins-Loveland MSA       2012      310835
25  Fort Collins-Loveland MSA       2013      316494
26  Fort Collins-Loveland MSA       2014      324122
27  Fort Collins-Loveland MSA       2015      331933
28         Grand Junction MSA       2009      147851
29         Grand Junction MSA       2010      146723
30         Grand Junction MSA       2011      147380
31         Grand Junction MSA       2012      147724
32         Grand Junction MSA       2013      147699
33         Grand Junction MSA       2014      148255
34         Grand Junction MSA       2015      148813
35                Greeley MSA       2009      248193
36                Greeley MSA       2010      252825
37                Greeley MSA       2011      258737
38                Greeley MSA       2012      264189
39                Greeley MSA       2013      270560
40                Greeley MSA       2014      277670
41                Greeley MSA       2015      284966
42                 Pueblo MSA       2009      157846
43                 Pueblo MSA       2010      159063
44                 Pueblo MSA       2011      160213
45                 Pueblo MSA       2012      160840
46                 Pueblo MSA       2013      161320
47                 Pueblo MSA       2014      161875
48                 Pueblo MSA       2015      162431

In [77]:
df['periodyear']=df['periodyear'].astype(int)
pop['periodyear']=pop['periodyear'].astype(int)

In [78]:
merge=pd.merge(df,pop,left_on=['areaname','periodyear'],right_on=['areaname','periodyear'])
merge

,areaname,areatyname,area,periodyear,indcodty,indcode,indcodetitle,occodetype,occodetydesc,occcode,...,response,mean,entrywg,experience,pct10,pct25,median,pct75,pct90,population
0,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,110000,...,75,79180.0,44856.0,96343.0,36707.0,55203.0,75767.0,NaN,NaN,159063
1,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,111021,...,74,81949.0,45908.0,99969.0,37604.0,55493.0,74416.0,NaN,NaN,159063
2,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,112022,...,61,75030.0,53688.0,85702.0,49753.0,56604.0,65304.0,NaN,NaN,159063
3,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113011,...,88,76405.0,42518.0,93349.0,23560.0,60126.0,80679.0,NaN,NaN,159063
4,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113021,...,70,103265.0,87338.0,111228.0,81820.0,92446.0,103040.0,NaN,NaN,159063
5,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113031,...,67,70900.0,48507.0,82097.0,44599.0,51408.0,61098.0,NaN,NaN,159063
6,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113049,...,73,98070.0,76794.0,108708.0,72581.0,81809.0,99943.0,NaN,NaN,159063
7,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113061,...,83,107086.0,81363.0,119947.0,77981.0,84878.0,107355.0,NaN,NaN,159063
8,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,113071,...,83,90883.0,66265.0,103192.0,66394.0,76380.0,97766.0,NaN,NaN,159063
9,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119021,...,80,77607.0,54772.0,89025.0,46748.0,64611.0,79703.0,NaN,NaN,159063
10,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119033,...,40,71595.0,48599.0,83093.0,45538.0,54760.0,68536.0,NaN,NaN,159063
11,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119041,...,88,128704.0,104509.0,140801.0,99909.0,110907.0,122488.0,NaN,NaN,159063
12,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119051,...,88,56027.0,34353.0,66864.0,32859.0,36173.0,44213.0,NaN,NaN,159063
13,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119111,...,87,72406.0,36123.0,90547.0,33101.0,37293.0,67508.0,NaN,NaN,159063
14,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119121,...,100,105091.0,82313.0,116480.0,82559.0,84542.0,101930.0,NaN,NaN,159063
15,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119131,...,100,68645.0,54636.0,75650.0,54338.0,54954.0,57938.0,NaN,NaN,159063
16,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119141,...,100,30572.0,16032.0,37843.0,15680.0,16013.0,24760.0,NaN,NaN,159063
17,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119151,...,83,60842.0,45363.0,68581.0,42784.0,47537.0,56470.0,NaN,NaN,159063
18,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,119199,...,81,96155.0,63608.0,112428.0,53699.0,80563.0,101029.0,NaN,NaN,159063
19,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,130000,...,79,55406.0,33934.0,66143.0,31342.0,39468.0,51544.0,NaN,NaN,159063
20,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131022,...,50,62343.0,31406.0,77812.0,27922.0,35074.0,54384.0,NaN,NaN,159063
21,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131023,...,82,54232.0,38539.0,62078.0,35997.0,42770.0,52567.0,NaN,NaN,159063
22,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131041,...,84,49592.0,25951.0,61413.0,24709.0,29521.0,43724.0,NaN,NaN,159063
23,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131051,...,80,55464.0,38672.0,63860.0,35994.0,42589.0,53379.0,NaN,NaN,159063
24,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131072,...,92,57949.0,43999.0,64925.0,41819.0,46869.0,56364.0,NaN,NaN,159063
25,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131073,...,75,39918.0,24445.0,47655.0,22116.0,26942.0,35631.0,NaN,NaN,159063
26,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131078,...,71,51591.0,33492.0,60640.0,30093.0,39841.0,47920.0,NaN,NaN,159063
27,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131081,...,100,58512.0,38428.0,68553.0,35153.0,41580.0,58977.0,NaN,NaN,159063
28,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131111,...,71,63944.0,34028.0,78903.0,27356.0,41584.0,63137.0,NaN,NaN,159063
29,Pueblo MSA,Metropolitan Statistical Area,39380,2010,10,0,Total All,8,SOC 2000,131161,...,88,41435.0,31961.0,46172.0,30322.0,32684.0,36546.0,NaN,NaN,159063
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19568,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,499099,...,80,28636.0,17119.0,34394.0,16659.0,17811.0,20738.0,43390.0,46007.0,160840
19569,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,510000,...,71,35827.0,22229.0,42626.0,19841.0,25198.0,34256.0,43075.0,53964.0,160840
19570,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,511011,...,74,63755.0,39098.0,76083.0,33281.0,46633.0,64934.0,77738.0,95891.0,160840
19571,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,512041,...,100,28321.0,21873.0,31545.0,20784.0,22521.0,26924.0,33593.0,38252.0,160840
19572,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,513011,...,63,25771.0,19481.0,28916.0,18303.0,20875.0,24441.0,29070.0,37677.0,160840
19573,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,513021,...,71,26973.0,17161.0,31879.0,17040.0,18763.0,23760.0,35952.0,43477.0,160840
19574,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,513099,...,80,25553.0,18165.0,29247.0,17281.0,19366.0,23683.0,32902.0,36515.0,160840
19575,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,514031,...,67,33461.0,27027.0,36678.0,25410.0,27168.0,30098.0,41312.0,45676.0,160840
19576,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,514041,...,86,33205.0,24266.0,37674.0,22191.0,25738.0,31742.0,40251.0,45758.0,160840
19577,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,514121,...,79,33516.0,25744.0,37402.0,24008.0,26466.0,29774.0,39629.0,47549.0,160840
19578,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,515112,...,78,36046.0,25043.0,41548.0,24432.0,28417.0,34525.0,44234.0,52776.0,160840
19579,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,516011,...,89,18974.0,17100.0,19910.0,16481.0,17365.0,18840.0,21034.0,23362.0,160840
19580,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,517021,...,67,31652.0,21718.0,36619.0,20777.0,22638.0,33049.0,38864.0,44079.0,160840
19581,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,518031,...,89,46012.0,33990.0,52024.0,32200.0,38581.0,44749.0,54173.0,63755.0,160840
19582,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,519061,...,60,39545.0,29262.0,44687.0,25299.0,34035.0,40798.0,44721.0,47075.0,160840
19583,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,519083,...,67,38568.0,26159.0,44773.0,22747.0,29647.0,38153.0,47682.0,55982.0,160840
19584,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,519151,...,60,25400.0,19677.0,28262.0,18202.0,20760.0,23542.0,29377.0,36385.0,160840
19585,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,530000,...,67,31801.0,18324.0,38540.0,17403.0,19817.0,28029.0,38467.0,45679.0,160840
19586,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,531021,...,55,56624.0,36606.0,66634.0,28356.0,42898.0,61306.0,71577.0,83549.0,160840
19587,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,531031,...,84,57089.0,35023.0,68121.0,32157.0,39986.0,60611.0,70090.0,83336.0,160840
19588,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,533031,...,53,23147.0,17014.0,26213.0,16566.0,17577.0,19276.0,29130.0,36810.0,160840
19589,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,533032,...,65,46379.0,24825.0,57155.0,24655.0,28092.0,33353.0,37969.0,128730.0,160840
19590,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,533033,...,77,23881.0,17031.0,27306.0,16818.0,18209.0,21545.0,26879.0,36214.0,160840
19591,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,533041,...,83,24524.0,17030.0,28271.0,16827.0,18232.0,24768.0,29470.0,35020.0,160840
19592,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,536031,...,80,21060.0,17090.0,23045.0,16925.0,18475.0,21098.0,23429.0,25630.0,160840
19593,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,537051,...,72,31752.0,19188.0,38035.0,18022.0,21414.0,30340.0,41834.0,45716.0,160840
19594,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,537061,...,50,20361.0,17007.0,22039.0,16602.0,17668.0,19437.0,22966.0,27074.0,160840
19595,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,537062,...,78,31286.0,19942.0,36958.0,18762.0,22214.0,30404.0,40812.0,44933.0,160840
19596,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,537064,...,57,25864.0,17075.0,30258.0,16857.0,18307.0,27162.0,33078.0,36034.0,160840
19597,Pueblo MSA,Metropolitan Statistical Area,39380,2012,10,0,Total All,14,SOC 2010,537081,...,50,28213.0,19651.0,32494.0,18348.0,21838.0,28401.0,34109.0,37752.0,160840

In [79]:
merge.keys()

Index(['areaname', 'areatyname', 'area', 'periodyear', 'indcodty', 'indcode',
       'indcodetitle', 'occodetype', 'occodetydesc', 'occcode', 'codetitle',
       'wagesource', 'wagesrdesc', 'ratetype', 'ratetydesc', 'empcount',
       'response', 'mean', 'entrywg', 'experience', 'pct10', 'pct25', 'median',
       'pct75', 'pct90', 'population'],
      dtype='object')

In [80]:
merge=merge.drop(columns=['areatyname','area','indcodty', 'indcode', 'indcodetitle', 'occodetype','occodetydesc','occcode','wagesource','wagesrdesc', 'ratetype', 'ratetydesc','response'])

In [81]:
merge.keys()

Index(['areaname', 'periodyear', 'codetitle', 'empcount', 'mean', 'entrywg',
       'experience', 'pct10', 'pct25', 'median', 'pct75', 'pct90',
       'population'],
      dtype='object')

In [82]:
merge=merge.drop_duplicates(subset=None, keep='first', inplace=False)
merge.shape

(19598, 13)

In [83]:
#merge=merge.dropna(how='all',inplace=True)

In [84]:
print(merge['periodyear'].unique())

[2010 2011 2009 2014 2013 2012 2015]

In [85]:
#merge.to_csv(r'C:\Users\jflan\Downloads\Merged_Employment_Wages_in_Colorado.csv')